-- =============================================================================
-- bundle_3_recent_062_069.sql
-- Generated by Codex from supabase/sql/*.sql. DO NOT EDIT ORIGINAL SQL FILES.
-- This bundle is for a blank/company Supabase setup via SQL Editor.
-- Execute bundle_1, verify, then bundle_2, verify, then bundle_3.
-- DB execution was NOT performed when generating this file.
--
-- Included source files:
--   - 062_custom_request_order_unique_active_application.sql
--   - 063_gate_deliverable_storage_by_order_completion.sql
--   - 064_subscription_billing_period_schema.sql
--   - 065_anchor_weekly_question_usage.sql
--   - 066_review_eligibility_billing_events.sql
--   - 067_mentor_subscription_pricing.sql
--   - 068_subscription_renewal_rpc.sql
--   - 069_subscription_cancel_refund_request.sql
--
-- Excluded source files:
--   - 002_app_core_schema_draft.sql
--   - 036_p1_prelaunch_rls_tightening.sql
--
-- Dry-run / verification notes:
--   - 062 duplicate-check SELECT removed; the unique index statement uses non-concurrent CREATE UNIQUE INDEX.
--   - 064 dry-run SELECT section removed; original file has backfill probes for non-empty DBs.
--   - 065 and 066 dry-run checks are comments only and remain non-executable.
--   - 067 DRY RUN SELECTs removed; duplicate guard remains inside migration.
--   - 069 VERIFY SELECTs are comments only and remain non-executable.
-- =============================================================================


-- ===== 062_custom_request_order_unique_active_application.sql =====

-- 062_custom_request_order_unique_active_application.sql
-- Purpose: prevent duplicate custom-request orders and duplicate escrow holds caused by double submit.
--
-- Apply order:
--   1) Run the duplicate-check SELECT below first.
--   2) If it returns any rows, stop and resolve the duplicate orders manually before creating the index.
--   3) If it returns 0 rows, run the CREATE UNIQUE INDEX statement.
--
-- Notes:
--   - This file does not modify escrow RPCs 054~057 and does not relax RLS.
--   - The index is partial: cancelled/canceled/refunded/rejected orders are excluded so a student can reorder
--     after cancellation/refund.
--   - CREATE INDEX must not run inside an explicit transaction block.

-- [bundle note] Original duplicate-check SELECT removed from this one-pass bundle.
-- Run the check separately if you are applying to a non-empty database.

create unique index if not exists ux_cro_active_application_once
  on public.custom_request_orders ((
    coalesce(selected_application_id, application_id, custom_request_application_id)
  ))
  where coalesce(selected_application_id, application_id, custom_request_application_id) is not null
    and lower(coalesce(payment_status, '')) not in ('cancelled', 'canceled', 'refunded')
    and lower(coalesce(status, '')) not in ('cancelled', 'canceled', 'refunded', 'rejected')
    and lower(coalesce(state, '')) not in ('cancelled', 'canceled', 'refunded', 'rejected')
    and lower(coalesce(order_status, '')) not in ('cancelled', 'canceled', 'refunded', 'rejected');


-- ===== 063_gate_deliverable_storage_by_order_completion.sql =====

-- 063_gate_deliverable_storage_by_order_completion.sql
-- Purpose: prevent students from bypassing the server download action by creating a direct
-- signed URL for custom-order deliverable storage objects before order acceptance/completion.
--
-- Apply order:
--   1) Apply after 010_p0_custom_order_deliverable_files_storage.sql and the app deploy that
--      strips storage_path from pre-completion student views.
--   2) Run the policy inspection query below before and after applying this file.
--
-- Rollback:
--   drop policy if exists "custom_order_deliverable_storage_read_party" on storage.objects;
--   create policy "custom_order_deliverable_storage_read_party"
--     on storage.objects
--     for select
--     to authenticated
--     using (
--       bucket_id = 'custom-order-deliverables'
--       and public.user_is_party_to_cro_storage_path(name)
--     );
--
-- Inspect:
--   select policyname, cmd, roles, qual
--   from pg_policies
--   where schemaname = 'storage'
--     and tablename = 'objects'
--     and policyname like 'custom_order_deliverable%';

create or replace function public.cro_primary_status_norm(o public.custom_request_orders)
returns text
language sql
stable
security definer
set search_path = public
as $f$
  select lower(coalesce(
    nullif(btrim(o.status), ''),
    nullif(btrim(o.state), ''),
    nullif(btrim(o.order_status), ''),
    nullif(btrim(o.stage), ''),
    ''
  ));
$f$;

create or replace function public.cro_student_can_read_deliverable_storage(o public.custom_request_orders)
returns boolean
language sql
stable
security definer
set search_path = public
as $f$
  select case
    when public.cro_primary_status_norm(o) in (
      'cancelled',
      'canceled',
      'refunded',
      'rejected',
      'disputed',
      'dispute_resolved'
    ) then false
    when public.cro_primary_status_norm(o) in ('completed', 'accepted', 'finished') then true
    when public.cro_primary_status_norm(o) in (
      'delivered',
      'delivered_pending_review',
      'waiting_review',
      'pending_review',
      'redelivered',
      'delivery_submitted',
      'in_review',
      'paid'
    ) then false
    when o.completed_at is not null or o.accepted_at is not null then true
    else false
  end;
$f$;

create or replace function public.user_can_read_cro_deliverable_storage_path(p_name text)
returns boolean
language sql
stable
security definer
set search_path = public
as $f$
  select exists (
    select 1
    from public.custom_request_orders o
    where o.id = public.cro_uuid_from_deliverable_storage_path(p_name)
      and (
        (select public.is_admin()) = true
        or o.mentor_id = (select auth.uid())
        or (
          (
            o.student_id = (select auth.uid())
            or o.buyer_id = (select auth.uid())
            or o.client_id = (select auth.uid())
            or o.user_id = (select auth.uid())
            or o.author_id = (select auth.uid())
            or o.requester_id = (select auth.uid())
          )
          and public.cro_student_can_read_deliverable_storage(o)
        )
      )
  );
$f$;

drop policy if exists "custom_order_deliverable_storage_read_party" on storage.objects;
create policy "custom_order_deliverable_storage_read_party"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'custom-order-deliverables'
    and public.user_can_read_cro_deliverable_storage_path(name)
  );


-- ===== 064_subscription_billing_period_schema.sql =====

-- =============================================================================
-- 064_subscription_billing_period_schema.sql
-- Purpose: P1 foundation for monthly subscription renewal.
-- Scope:
--   1) Add billing-period columns to public.subscriptions.
--   2) Add public.subscription_billing_events.
--   3) Backfill existing subscriptions and record the initial payment as a
--      succeeded billing event.
--
-- Not included in P1:
--   - No automatic renewal batch/cron.
--   - No additional cash debit RPC.
--   - No changes to record_subscription_cash_debit (019).
--   - No changes to custom request escrow RPCs (054~057).
--   - No change to uq_subscriptions_pair lifetime one-row model.
--
-- Execution order in Supabase SQL Editor:
--   A. Review the dry-run SELECT results in section 0.
--   B. If counts look correct, run the whole file.
--
-- Rollback notes:
--   - Drop table public.subscription_billing_events after clearing
--     subscriptions.last_billing_event_id.
--   - Drop the added subscriptions columns if P1 must be fully reverted.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0) Dry-run probes removed from this one-pass bundle.
--    Review the original file if applying to a non-empty database.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- 1) subscriptions: billing period columns.
-- -----------------------------------------------------------------------------
alter table public.subscriptions
  add column if not exists started_at timestamptz,
  add column if not exists current_period_start timestamptz,
  add column if not exists current_period_end timestamptz,
  add column if not exists next_billing_at timestamptz,
  add column if not exists billing_cycle text default 'monthly',
  add column if not exists cancel_at_period_end boolean not null default false,
  add column if not exists cancel_requested_at timestamptz,
  add column if not exists canceled_at timestamptz,
  add column if not exists expired_at timestamptz,
  add column if not exists last_renewed_at timestamptz,
  add column if not exists last_billing_event_id uuid,
  add column if not exists last_payment_id uuid,
  add column if not exists grace_until timestamptz;

alter table public.subscriptions
  alter column billing_cycle set default 'monthly';

do $$
declare
  v_constraint_name text;
begin
  for v_constraint_name in
    select c.conname
    from pg_constraint c
    where c.conrelid = 'public.subscriptions'::regclass
      and c.contype = 'c'
      and pg_get_constraintdef(c.oid) ilike '%status%'
  loop
    execute format('alter table public.subscriptions drop constraint if exists %I', v_constraint_name);
  end loop;
end
$$;

alter table public.subscriptions
  add constraint subscriptions_status_check
  check (
    status in (
      'pending',
      'active',
      'past_due',
      'cancel_scheduled',
      'canceled',
      'expired',
      'refunded'
    )
  );

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.subscriptions'::regclass
      and conname = 'subscriptions_last_payment_id_fkey'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_last_payment_id_fkey
      foreign key (last_payment_id) references public.payments(id) on delete set null;
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- 2) subscription_billing_events: append-only billing history.
-- -----------------------------------------------------------------------------
create table if not exists public.subscription_billing_events (
  id uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references public.subscriptions(id) on delete cascade,
  student_id uuid not null references public.users(id) on delete cascade,
  mentor_id uuid not null references public.users(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'initial',
      'renewal',
      'renewal_failed',
      'expired',
      'cancel_scheduled',
      'canceled',
      'refund'
    )
  ),
  status text not null check (
    status in (
      'pending',
      'processing',
      'succeeded',
      'failed',
      'skipped',
      'refunded'
    )
  ),
  period_start timestamptz,
  period_end timestamptz,
  billing_at timestamptz,
  amount_cents int,
  plan_tier text,
  plan_id uuid,
  idempotency_key text unique,
  ledger_id uuid references public.cash_ledger(id) on delete set null,
  payment_id uuid references public.payments(id) on delete set null,
  failure_code text,
  failure_message text,
  attempt_count int not null default 0,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.subscription_billing_events enable row level security;

drop policy if exists "subscription_billing_events_select_parties" on public.subscription_billing_events;
create policy "subscription_billing_events_select_parties" on public.subscription_billing_events
  for select to authenticated
  using (
    (select auth.uid()) in (student_id, mentor_id)
    or (select public.is_admin()) = true
  );

-- No INSERT/UPDATE/DELETE policies for authenticated users.
-- Server writes use service_role, which bypasses RLS.
grant select on table public.subscription_billing_events to authenticated;
grant all on table public.subscription_billing_events to service_role;

create index if not exists idx_subscription_billing_events_subscription_period
  on public.subscription_billing_events (subscription_id, period_start);

create index if not exists idx_subscription_billing_events_pair_status
  on public.subscription_billing_events (student_id, mentor_id, status);

create index if not exists idx_subscription_billing_events_pending_billing_at
  on public.subscription_billing_events (billing_at)
  where status = 'pending';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.subscriptions'::regclass
      and conname = 'subscriptions_last_billing_event_id_fkey'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_last_billing_event_id_fkey
      foreign key (last_billing_event_id)
      references public.subscription_billing_events(id)
      on delete set null;
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- 3) Backfill existing subscriptions.
--    Month-end policy: PostgreSQL interval arithmetic clamps missing month days
--    to the target month's last day (for example Jan 31 + 1 month = Feb 28/29).
-- -----------------------------------------------------------------------------
update public.subscriptions
set
  started_at = coalesce(started_at, created_at),
  current_period_start = coalesce(current_period_start, coalesce(started_at, created_at)),
  current_period_end = coalesce(current_period_end, coalesce(started_at, created_at) + interval '1 month'),
  next_billing_at = coalesce(next_billing_at, coalesce(current_period_end, coalesce(started_at, created_at) + interval '1 month')),
  billing_cycle = coalesce(nullif(billing_cycle, ''), 'monthly'),
  last_payment_id = coalesce(last_payment_id, payment_id)
where started_at is null
   or current_period_start is null
   or current_period_end is null
   or next_billing_at is null
   or billing_cycle is null
   or billing_cycle = ''
   or (last_payment_id is null and payment_id is not null);

with initial_source as (
  select
    s.id as subscription_id,
    s.student_id,
    s.mentor_id,
    s.plan_tier,
    s.plan_id,
    s.payment_id,
    s.current_period_start,
    s.current_period_end,
    coalesce(cl.created_at, p.created_at, s.created_at) as billing_at,
    coalesce(
      abs(cl.delta_cents)::int,
      mp.amount_cents::int,
      case
        when p.amount is not null and p.amount > 0 then round(p.amount * 100)::int
        else null
      end
    ) as amount_cents,
    cl.id as ledger_id
  from public.subscriptions s
  left join public.payments p on p.id = s.payment_id
  left join public.mentor_plans mp on mp.id = s.plan_id
  left join lateral (
    select l.id, l.delta_cents, l.created_at
    from public.cash_ledger l
    where l.ref_type = 'subscriptions'
      and l.ref_id = s.id
      and l.user_id = s.student_id
      and l.delta_cents < 0
    order by l.created_at asc
    limit 1
  ) cl on true
)
insert into public.subscription_billing_events (
  subscription_id,
  student_id,
  mentor_id,
  event_type,
  status,
  period_start,
  period_end,
  billing_at,
  amount_cents,
  plan_tier,
  plan_id,
  idempotency_key,
  ledger_id,
  payment_id,
  created_at,
  processed_at
)
select
  src.subscription_id,
  src.student_id,
  src.mentor_id,
  'initial',
  'succeeded',
  src.current_period_start,
  src.current_period_end,
  src.billing_at,
  src.amount_cents,
  src.plan_tier,
  src.plan_id,
  'sub_initial:' || src.subscription_id::text,
  src.ledger_id,
  src.payment_id,
  now(),
  src.billing_at
from initial_source src
on conflict (idempotency_key) do nothing;

update public.subscriptions s
set
  last_billing_event_id = coalesce(s.last_billing_event_id, e.id),
  last_payment_id = coalesce(s.last_payment_id, e.payment_id, s.payment_id)
from public.subscription_billing_events e
where e.subscription_id = s.id
  and e.event_type = 'initial'
  and e.idempotency_key = 'sub_initial:' || s.id::text
  and (s.last_billing_event_id is null or s.last_payment_id is null);

-- -----------------------------------------------------------------------------
-- 4) Verification queries.
-- -----------------------------------------------------------------------------
select
  count(*) as initial_billing_events_total,
  count(*) filter (where event_type = 'initial' and status = 'succeeded') as initial_succeeded_total
from public.subscription_billing_events;

select
  s.id,
  s.status,
  s.started_at,
  s.current_period_start,
  s.current_period_end,
  s.next_billing_at,
  s.last_billing_event_id,
  e.idempotency_key as initial_event_key,
  e.amount_cents as initial_event_amount_cents
from public.subscriptions s
left join public.subscription_billing_events e on e.id = s.last_billing_event_id
order by s.created_at asc;


-- ===== 065_anchor_weekly_question_usage.sql =====

-- =============================================================================
-- 065_anchor_weekly_question_usage.sql
-- Purpose: Question quota windows reset every 7 days from the subscription
--          start anchor, not on the calendar Monday boundary.
--
-- Prerequisite:
--   - 064_subscription_billing_period_schema.sql has been applied.
--
-- Scope:
--   - Replace get_weekly_question_usage(uuid, uuid) only.
--   - No cash debit, renewal batch, escrow, or custom request changes.
--
-- Dry-run checks before/after applying:
--   select id, student_id, mentor_id, status, started_at, created_at
--   from public.subscriptions
--   where status = 'active'
--   order by created_at desc
--   limit 20;
--
-- Formula:
--   anchor = coalesce(subscriptions.started_at, subscriptions.created_at)
--   period_start = anchor + floor((now - anchor) / 7 days) * 7 days
--   period_end = period_start + 7 days
-- =============================================================================

create or replace function public.get_weekly_question_usage(
  p_student_id uuid,
  p_mentor_id uuid
)
returns json
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_anchor timestamptz;
  v_week_start timestamptz;
  v_week_end timestamptz;
  v_elapsed_seconds numeric;
  v_period_index integer;
  v_used integer := 0;
  v_plan_tier text;
  v_limit integer := 0;
begin
  if p_student_id is null or p_mentor_id is null then
    raise exception 'p_student_id and p_mentor_id are required';
  end if;

  select
    s.plan_tier,
    coalesce(s.started_at, s.created_at)
  into v_plan_tier, v_anchor
  from public.subscriptions s
  where s.student_id = p_student_id
    and s.mentor_id = p_mentor_id
    and lower(coalesce(s.status, '')) = 'active'
  order by s.created_at desc
  limit 1;

  v_limit := case lower(coalesce(v_plan_tier, ''))
    when 'limited' then 4
    when 'standard' then 9
    when 'premium' then 999
    else 0
  end;

  if v_anchor is not null then
    v_elapsed_seconds := extract(epoch from (now() - v_anchor));
    v_period_index := greatest(0, floor(v_elapsed_seconds / 604800.0)::integer);
    v_week_start := v_anchor + (v_period_index * interval '7 days');
    v_week_end := v_week_start + interval '7 days';

    select count(*)::integer into v_used
    from public.question_threads qt
    inner join public.mentor_student_rooms r on r.id = qt.mentor_student_room_id
    where r.student_id = p_student_id
      and r.mentor_id = p_mentor_id
      and qt.status = 'confirmed'
      and coalesce(qt.updated_at, qt.created_at) >= v_week_start
      and coalesce(qt.updated_at, qt.created_at) < v_week_end;
  end if;

  return json_build_object(
    'used', coalesce(v_used, 0),
    'limit', v_limit,
    'plan_tier', v_plan_tier,
    'remaining', greatest(0, v_limit - coalesce(v_used, 0)),
    'can_ask', coalesce(v_used, 0) < v_limit,
    'week_start', v_week_start,
    'week_end', v_week_end
  );
end;
$function$;

revoke all on function public.get_weekly_question_usage(uuid, uuid) from public;
grant execute on function public.get_weekly_question_usage(uuid, uuid) to authenticated;
grant execute on function public.get_weekly_question_usage(uuid, uuid) to service_role;

comment on function public.get_weekly_question_usage(uuid, uuid) is
  'Weekly question usage: confirmed threads counted in a 7-day window anchored to subscriptions.started_at (fallback created_at), independently per student-mentor subscription.';


-- ===== 066_review_eligibility_billing_events.sql =====

-- =============================================================================
-- 066_review_eligibility_billing_events.sql
-- Purpose: Review eligibility is based on 2+ successful paid billing events for
--          the same student/mentor pair.
--
-- Prerequisite:
--   - 064_subscription_billing_period_schema.sql has been applied.
--
-- Scope:
--   - Replace public.check_review_eligibility(uuid, uuid).
--   - Keep reviews storage/display/reply/moderation logic unchanged.
--   - No subscription renewal debit, cron, escrow, or custom request changes.
--
-- Dry-run checks:
--   select student_id, mentor_id, count(*) as succeeded_paid_events
--   from public.subscription_billing_events
--   where status = 'succeeded'
--     and event_type in ('initial', 'renewal')
--     and coalesce(amount_cents, 0) > 0
--     and coalesce(lower(trim(plan_tier)), '') not in ('free', 'trial')
--     and coalesce(lower(trim(plan_tier)), '') not like '%trial%'
--   group by student_id, mentor_id
--   order by succeeded_paid_events desc;
-- =============================================================================

create or replace function public.check_review_eligibility(
  p_mentor_id uuid,
  p_student_id uuid
) returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  event_paid integer := 0;
  ledger_paid integer := 0;
  payment_paid integer := 0;
begin
  if p_mentor_id is null or p_student_id is null then
    return false;
  end if;

  select count(*)::integer
  into event_paid
  from public.subscription_billing_events e
  where e.student_id = p_student_id
    and e.mentor_id = p_mentor_id
    and e.status = 'succeeded'
    and e.event_type in ('initial', 'renewal')
    and coalesce(e.amount_cents, 0) > 0
    and coalesce(lower(trim(e.plan_tier)), '') not in ('free', 'trial')
    and coalesce(lower(trim(e.plan_tier)), '') not like '%trial%';

  if event_paid >= 2 then
    return true;
  end if;

  -- Fallback for old data if billing events are missing/incomplete.
  -- Count ledger rows first because a cash checkout has both payments and ledger;
  -- do not add the two counts together.
  select count(*)::integer
  into ledger_paid
  from public.subscriptions s
  join public.cash_ledger cl
    on cl.ref_type = 'subscriptions'
   and cl.ref_id = s.id
   and cl.user_id = p_student_id
   and cl.delta_cents < 0
  where s.student_id = p_student_id
    and s.mentor_id = p_mentor_id
    and coalesce(lower(trim(s.plan_tier)), '') not in ('free', 'trial')
    and coalesce(lower(trim(s.plan_tier)), '') not like '%trial%';

  if ledger_paid >= 2 then
    return true;
  end if;

  select count(*)::integer
  into payment_paid
  from public.payments p
  where (p.user_id = p_student_id or p.student_id = p_student_id or p.payer_id = p_student_id)
    and p.mentor_id = p_mentor_id
    and lower(trim(p.status)) in (
      'paid', 'succeeded', 'completed', 'complete', 'success',
      'captured', 'escrowed', 'paid_out'
    )
    and p.amount > 0
    and (
      coalesce(lower(trim(p.kind)), '') = 'subscription'
      or coalesce(p.metadata->>'source', '') = 'subscribe_checkout'
      or coalesce(p.data->>'source', '') = 'subscribe_checkout'
    );

  return greatest(event_paid, ledger_paid, payment_paid) >= 2;
end;
$$;

revoke all on function public.check_review_eligibility(uuid, uuid) from public, anon;
grant execute on function public.check_review_eligibility(uuid, uuid) to authenticated;

comment on function public.check_review_eligibility(uuid, uuid) is
  'Review eligibility: same student/mentor pair needs at least two successful paid subscription billing events (initial/renewal). Falls back to legacy subscription ledger/payment counts without summing duplicate sources.';


-- ===== 067_mentor_subscription_pricing.sql =====

-- 067_mentor_subscription_pricing.sql
-- Purpose: allow mentors to set subscription plan prices through public.mentor_plans.amount_cents.
--
-- Execution order:
-- 1) Review the DRY-RUN SELECT results below.
-- 2) If duplicate_rows returns any row, stop and resolve duplicates manually before running the migration.
-- 3) Run the whole file in Supabase SQL Editor.
--
-- Rollback notes:
-- - drop index if exists public.uq_mentor_plans_mentor_tier;
-- - alter table public.mentor_plans drop column if exists price_updated_at;
-- - seeded rows can be removed manually only if they were not edited/used.

-- [bundle note] Original DRY RUN SELECTs 1~3 removed from this one-pass bundle.
-- Review the original file if applying to a non-empty database.

begin;

alter table public.mentor_plans
  add column if not exists price_updated_at timestamptz;

do $$
declare
  duplicate_count integer;
begin
  select count(*)
    into duplicate_count
  from (
    select mentor_id, plan_tier
    from public.mentor_plans
    where mentor_id is not null
      and plan_tier in ('limited', 'standard', 'premium')
    group by mentor_id, plan_tier
    having count(*) > 1
  ) d;

  if duplicate_count > 0 then
    raise exception 'mentor_plans has duplicate mentor_id/plan_tier rows. Review DRY RUN 1 and resolve duplicates before creating the unique index.';
  end if;
end $$;

create unique index if not exists uq_mentor_plans_mentor_tier
  on public.mentor_plans (mentor_id, plan_tier);

-- Normalize legacy values accidentally stored as KRW in amount_cents.
update public.mentor_plans
set
  amount_cents = amount_cents * 100,
  updated_at = now(),
  price_updated_at = coalesce(price_updated_at, now())
where (
    (plan_tier = 'limited' and amount_cents between 39900 and 69900)
 or (plan_tier = 'standard' and amount_cents between 84900 and 149900)
 or (plan_tier = 'premium' and amount_cents between 189900 and 329900)
);

-- Prevent null/zero prices from becoming zero-cash checkout rows. Ranges are not enforced by DB.
update public.mentor_plans
set
  amount_cents = case plan_tier
    when 'limited' then 5500000
    when 'standard' then 11490000
    when 'premium' then 24990000
    else amount_cents
  end,
  updated_at = now(),
  price_updated_at = coalesce(price_updated_at, now())
where plan_tier in ('limited', 'standard', 'premium')
  and (amount_cents is null or amount_cents <= 0);

-- Seed every mentor with the three required tiers. Mentors may later edit prices freely.
with mentor_users as (
  select id
  from public.users
  where role = 'mentor'
),
tiers(plan_tier, label, amount_cents) as (
  values
    ('limited', 'Limited', 5500000),
    ('standard', 'Standard', 11490000),
    ('premium', 'Premium', 24990000)
)
insert into public.mentor_plans (
  mentor_id,
  plan_tier,
  label,
  amount_cents,
  created_at,
  updated_at,
  price_updated_at
)
select
  m.id,
  t.plan_tier,
  t.label,
  t.amount_cents,
  now(),
  now(),
  now()
from mentor_users m
cross join tiers t
on conflict (mentor_id, plan_tier) do nothing;

comment on column public.mentor_plans.price_updated_at is
  'Last time the mentor subscription price was changed. Ranges are soft-guided in UI, not DB-enforced.';

commit;


-- ===== 068_subscription_renewal_rpc.sql =====

-- =============================================================================
-- 068_subscription_renewal_rpc.sql
-- Purpose: P2 monthly subscription renewal debit RPC.
--
-- Safety:
--   - Does not modify 019 record_subscription_cash_debit.
--   - Does not touch custom request escrow RPCs 054~057.
--   - No negative wallet balance: wallet update requires balance >= amount.
--   - Idempotency layers:
--       1) subscription_billing_events.idempotency_key unique
--       2) cash_ledger.idempotency_key unique
--       3) subscriptions row SELECT ... FOR UPDATE
--
-- Execution:
--   Run after 064_subscription_billing_period_schema.sql.
--
-- Rollback:
--   revoke all on function public.process_subscription_renewal(uuid, timestamptz, bigint, text, timestamptz) from public;
--   drop function if exists public.process_subscription_renewal(uuid, timestamptz, bigint, text, timestamptz);
-- =============================================================================

create or replace function public.process_subscription_renewal(
  p_subscription_id uuid,
  p_period_end timestamptz,
  p_amount_cents bigint,
  p_idempotency_key text,
  p_processed_at timestamptz default now()
)
returns table (
  ok boolean,
  code text,
  message text,
  billing_event_id uuid,
  ledger_id uuid,
  next_period_start timestamptz,
  next_period_end timestamptz,
  wallet_balance_cents bigint,
  attempt_count int
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_sub public.subscriptions%rowtype;
  v_event public.subscription_billing_events%rowtype;
  v_event_id uuid;
  v_ledger_id uuid;
  v_wallet_balance bigint;
  v_period_start timestamptz;
  v_period_end timestamptz;
  v_attempt_count int;
begin
  if p_subscription_id is null then
    return query select false, 'invalid_subscription'::text, 'subscription_id is required'::text, null::uuid, null::uuid, null::timestamptz, null::timestamptz, null::bigint, 0::int;
    return;
  end if;

  if p_amount_cents is null or p_amount_cents <= 0 then
    return query select false, 'invalid_amount'::text, 'p_amount_cents must be positive'::text, null::uuid, null::uuid, null::timestamptz, null::timestamptz, null::bigint, 0::int;
    return;
  end if;

  if p_idempotency_key is null or length(trim(p_idempotency_key)) = 0 then
    return query select false, 'invalid_idempotency_key'::text, 'idempotency_key is required'::text, null::uuid, null::uuid, null::timestamptz, null::timestamptz, null::bigint, 0::int;
    return;
  end if;

  select *
    into v_sub
  from public.subscriptions
  where id = p_subscription_id
  for update;

  if not found then
    return query select false, 'not_found'::text, 'subscription not found'::text, null::uuid, null::uuid, null::timestamptz, null::timestamptz, null::bigint, 0::int;
    return;
  end if;

  if coalesce(v_sub.status, '') not in ('active', 'past_due') then
    return query select false, 'not_renewable_status'::text, 'subscription status is not renewable'::text, null::uuid, null::uuid, v_sub.current_period_start, v_sub.current_period_end, null::bigint, 0::int;
    return;
  end if;

  select *
    into v_event
  from public.subscription_billing_events
  where idempotency_key = p_idempotency_key
  for update;

  if found then
    if v_event.status = 'succeeded' then
      return query select true, 'already_succeeded'::text, 'renewal already processed'::text, v_event.id, v_event.ledger_id, v_event.period_start, v_event.period_end, null::bigint, coalesce(v_event.attempt_count, 0);
      return;
    end if;

    if v_event.status in ('pending', 'processing') then
      return query select false, 'already_processing'::text, 'renewal is already processing'::text, v_event.id, v_event.ledger_id, v_event.period_start, v_event.period_end, null::bigint, coalesce(v_event.attempt_count, 0);
      return;
    end if;

    update public.subscription_billing_events as e
    set
      event_type = 'renewal',
      status = 'processing',
      failure_code = null,
      failure_message = null,
      amount_cents = p_amount_cents::int,
      billing_at = p_processed_at,
      attempt_count = coalesce(attempt_count, 0) + 1,
      processed_at = null
    where e.id = v_event.id
    returning e.* into v_event;

    v_event_id := v_event.id;
    v_attempt_count := coalesce(v_event.attempt_count, 1);
  else
    v_period_start := coalesce(v_sub.current_period_end, p_period_end, p_processed_at);
    v_period_end := v_period_start + interval '1 month';

    insert into public.subscription_billing_events (
      subscription_id,
      student_id,
      mentor_id,
      event_type,
      status,
      period_start,
      period_end,
      billing_at,
      amount_cents,
      plan_tier,
      plan_id,
      idempotency_key,
      attempt_count,
      created_at
    )
    values (
      v_sub.id,
      v_sub.student_id,
      v_sub.mentor_id,
      'renewal',
      'processing',
      v_period_start,
      v_period_end,
      p_processed_at,
      p_amount_cents::int,
      v_sub.plan_tier,
      v_sub.plan_id,
      p_idempotency_key,
      1,
      p_processed_at
    )
    returning * into v_event;

    v_event_id := v_event.id;
    v_attempt_count := 1;
  end if;

  insert into public.cash_wallets (user_id, balance_cents)
  values (v_sub.student_id, 0)
  on conflict (user_id) do nothing;

  update public.cash_wallets
  set balance_cents = balance_cents - p_amount_cents
  where user_id = v_sub.student_id
    and balance_cents >= p_amount_cents
  returning balance_cents into v_wallet_balance;

  if not found then
    update public.subscription_billing_events as e
    set
      event_type = 'renewal_failed',
      status = 'failed',
      failure_code = 'insufficient_cash',
      failure_message = 'CASH_INSUFFICIENT',
      processed_at = p_processed_at
    where e.id = v_event_id
    returning e.attempt_count into v_attempt_count;

    update public.subscriptions
    set
      status = 'past_due',
      grace_until = coalesce(grace_until, p_processed_at + interval '2 days'),
      updated_at = p_processed_at,
      last_billing_event_id = v_event_id
    where id = v_sub.id;

    return query select false, 'insufficient_cash'::text, 'CASH_INSUFFICIENT'::text, v_event_id, null::uuid, v_event.period_start, v_event.period_end, null::bigint, coalesce(v_attempt_count, 1);
    return;
  end if;

  insert into public.cash_ledger (
    user_id,
    delta_cents,
    reason,
    ref_type,
    ref_id,
    idempotency_key,
    created_at
  )
  values (
    v_sub.student_id,
    -p_amount_cents,
    'subscription_renewal',
    'subscriptions',
    v_sub.id,
    p_idempotency_key,
    p_processed_at
  )
  on conflict (idempotency_key) do nothing
  returning id into v_ledger_id;

  if v_ledger_id is null then
    select id
      into v_ledger_id
    from public.cash_ledger
    where idempotency_key = p_idempotency_key;
  end if;

  v_period_start := coalesce(v_event.period_start, v_sub.current_period_end, p_period_end, p_processed_at);
  v_period_end := coalesce(v_event.period_end, v_period_start + interval '1 month');

  update public.subscription_billing_events as e
  set
    event_type = 'renewal',
    status = 'succeeded',
    ledger_id = v_ledger_id,
    processed_at = p_processed_at,
    failure_code = null,
    failure_message = null,
    period_start = v_period_start,
    period_end = v_period_end,
    amount_cents = p_amount_cents::int
  where e.id = v_event_id
  returning e.attempt_count into v_attempt_count;

  update public.subscriptions
  set
    status = 'active',
    current_period_start = v_period_start,
    current_period_end = v_period_end,
    next_billing_at = v_period_end,
    last_renewed_at = p_processed_at,
    last_billing_event_id = v_event_id,
    grace_until = null,
    updated_at = p_processed_at
  where id = v_sub.id;

  return query select true, 'succeeded'::text, 'renewal processed'::text, v_event_id, v_ledger_id, v_period_start, v_period_end, v_wallet_balance, coalesce(v_attempt_count, 1);
end;
$function$;

revoke all on function public.process_subscription_renewal(uuid, timestamptz, bigint, text, timestamptz) from public;
grant execute on function public.process_subscription_renewal(uuid, timestamptz, bigint, text, timestamptz) to service_role;


-- ===== 069_subscription_cancel_refund_request.sql =====

-- 069_subscription_cancel_refund_request.sql
-- P4: subscription cancel-at-period-end + prorated refund request metadata.
--
-- Execution order:
--   1) Run this whole file in Supabase SQL Editor.
--   2) Run the verification SELECTs below.
--   3) If unexpected duplicate pending subscription refunds appear, resolve them manually.
--
-- VERIFY 1: pending subscription refund rows after metadata exists
-- select subscription_id, count(*)
-- from public.refunds
-- where subscription_id is not null and status = 'pending'
-- group by subscription_id
-- having count(*) > 1;
--
-- VERIFY 2: subscription refunds that would sync status when approved
-- select r.id, r.subscription_id, r.payment_id, r.status, r.amount_cents
-- from public.refunds r
-- where coalesce(r.request_type, '') = 'subscription_prorated'
-- order by r.created_at desc
-- limit 20;

begin;

alter table public.refunds
  add column if not exists subscription_id uuid references public.subscriptions(id) on delete set null,
  add column if not exists request_type text,
  add column if not exists reason text;

create index if not exists idx_refunds_subscription_status
  on public.refunds (subscription_id, status, created_at desc)
  where subscription_id is not null;

create index if not exists idx_refunds_subscription_prorated_pending
  on public.refunds (subscription_id, created_at desc)
  where subscription_id is not null
    and status = 'pending'
    and request_type = 'subscription_prorated';

create or replace function public.sync_subscription_refunded_from_refund()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.status = 'succeeded'
     and coalesce(new.request_type, '') = 'subscription_prorated'
     and new.subscription_id is not null then
    update public.subscriptions s
    set
      status = 'refunded',
      cancel_at_period_end = false,
      canceled_at = coalesce(s.canceled_at, now()),
      expired_at = coalesce(s.expired_at, now()),
      next_billing_at = null,
      updated_at = now()
    where s.id = new.subscription_id;
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_refunds_sync_subscription_refunded on public.refunds;
create trigger trg_refunds_sync_subscription_refunded
  after update of status on public.refunds
  for each row
  when (new.status = 'succeeded')
  execute function public.sync_subscription_refunded_from_refund();

create or replace function public.keep_subscription_refunded_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.status = 'canceled'
     and exists (
       select 1
       from public.refunds r
       where r.status = 'succeeded'
         and coalesce(r.request_type, '') = 'subscription_prorated'
         and (
           r.subscription_id = new.id
           or (
             r.subscription_id is null
             and r.payment_id is not null
             and r.payment_id = new.payment_id
           )
         )
     ) then
    new.status := 'refunded';
    new.cancel_at_period_end := false;
    new.canceled_at := coalesce(new.canceled_at, now());
    new.expired_at := coalesce(new.expired_at, now());
    new.next_billing_at := null;
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_subscriptions_keep_refunded_status on public.subscriptions;
create trigger trg_subscriptions_keep_refunded_status
  before update of status on public.subscriptions
  for each row
  execute function public.keep_subscription_refunded_status();

comment on column public.refunds.subscription_id is
  'P4 subscription refund request target. Student requests are inserted by server action; admin approval remains existing refund RPC.';
comment on column public.refunds.request_type is
  'Use subscription_prorated for student-requested remaining-period subscription refunds.';
comment on function public.sync_subscription_refunded_from_refund() is
  'P4: When a subscription_prorated refund is approved, mark the target subscription refunded.';
comment on function public.keep_subscription_refunded_status() is
  'P4: Preserve refunded subscription status when legacy refund RPC updates by payment_id to canceled.';

commit;
